Repository goldforestdev/CommuterBus, pull requests merged in 2019-10, with the labels that each got.

#12 현재 위치 가져오기 구현 중
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/model/BusLine.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/current/CurrentContract.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/current/CurrentFragment.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/current/CurrentPresenter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/splash/SplashActivity.kt
  app/src/main/res/layout/activity_spalsh.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/raw/ani_splash_bus.json
  app/src/main/res/values/strings.xml
Labels: main feature

#13 Firebase DB 연동 및 data 읽어 오기
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/com/hppk/sw/hppkcommuterbus/firebase/FireBaseDB.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/MainActivity.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesAdapter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesContract.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesFragment.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesPresenter.kt
  build.gradle
Labels: enhancement

#14 Firebase DB 관련 로직 Repository 패턴으로 분리
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/model/Exceptions.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/BusLineRepository.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/source/BusLineDataSource.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/source/local/LocalBusLineDao.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/source/remote/FirebaseBusLineDao.kt
Labels: refactoring

#15 현재 위치 기준으로 주변 버스 정류장 보여주기 #10
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/model/Exceptions.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/BusLineRepository.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/source/BusLineDataSource.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/source/local/LocalBusLineDao.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/source/remote/FirebaseBusLineDao.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/current/CurrentContract.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/current/CurrentFragment.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/current/CurrentPresenter.kt
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: main feature

#16 DB Bus list 표시 하기 구현 중(변경된 Interface로 합치기 위해 임시 코드 업로드)
  .idea/codeStyles/Project.xml
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/MainActivity.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesAdapter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesContract.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesFragment.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/util/Utils.kt
  app/src/main/res/layout/fragment_bus_lines.xml
  app/src/main/res/layout/item_bus_list.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#18 버스 라인 리스트 가져오는 로직 이동 #17
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/MainActivity.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/splash/SplashActivity.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/splash/SplashContract.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/splash/SplashPresenter.kt
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: refactoring

#19 BusList에서 버스 클릭 시 해당 정보가 보이는 Activity연결
  .idea/codeStyles/Project.xml
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesAdapter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesFragment.kt
  app/src/main/res/layout/fragment_bus_lines.xml
Labels: enhancement

#20 출.퇴근 버스 분리되어 List 표시 되도록
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hppk/sw/hppkcommuterbus/application/CommuterBusApplication.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesAdapter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesFragment.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/details/BusStopsAdapter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/details/LineDetailsActivity.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/util/Utils.kt
  app/src/main/res/layout/fragment_bus_lines.xml
Labels: enhancement

#21 즐겨 찾기 기능 구현
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/com/hppk/sw/hppkcommuterbus/application/CommuterBusApplication.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/local/FavoritesLocalDataSource.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/firebase/FireBaseDB.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesAdapter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesFragment.kt
  app/src/main/res/layout/fragment_bus_lines.xml
  app/src/main/res/layout/item_bus_list.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#25 FIX - 버스 정류장 선택 시 앱 죽는 문제 #24
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/details/LineDetailsActivity.kt
Labels: bug

#27 출근 버스 알람 기본 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hppk/sw/hppkcommuterbus/manager/BusAlarmManager.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/manager/NotiManager.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/AlarmReceiver.kt
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: main feature

#29 Bottom menu에서 뒤로 가기 시 앱 종료하도록 수정
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesFragment.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/current/CurrentFragment.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/mypage/MyPageFragment.kt
Labels: bug

#30 퇴근 알람 기본 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hppk/sw/hppkcommuterbus/manager/BusAlarmManager.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/AlarmReceiver.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/GeofenceBroadcastReceiver.kt
Labels: main feature

#31 현재 위치 버튼 추가
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/current/CurrentFragment.kt
  app/src/main/res/drawable/ic_gps_indicator.png
  app/src/main/res/drawable/ic_gps_indicator_press.png
  app/src/main/res/drawable/selector_gps_indicator.xml
  app/src/main/res/layout/fragment_map.xml
Labels: main feature

#33 Alarm이 반복적으로 수행되도록 수정
  app/src/main/java/com/hppk/sw/hppkcommuterbus/manager/BusAlarmManager.kt
Labels: bug

#36 FIX - 앱 죽는 문제 수정
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/AlarmReceiver.kt
Labels: bug

#37 Settings UI 기본 구현
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/MainActivity.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/settings/SettingsActivity.kt
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/settings_activity.xml
  app/src/main/res/menu/menu_options.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/root_preferences.xml
Labels: main feature

#38 Alarm 울리지 않는 문제 수정
  app/src/main/java/com/hppk/sw/hppkcommuterbus/application/CommuterBusApplication.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/manager/BusAlarmManager.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/manager/NotiManager.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/AlarmReceiver.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/splash/SplashActivity.kt
Labels: bug

#39 Favorite 가져오는 로직 FavoriteRepo로 분리
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/local/LocalDataSource.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/FavoriteRepository.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/source/local/PrefFavoriteDao.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesContract.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesFragment.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesPresenter.kt
Labels: refactoring

#40 busline, busstop 이름 얻는 로직의 단일화
  app/src/main/java/com/hppk/sw/hppkcommuterbus/application/CommuterBusApplication.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/model/BusLine.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesAdapter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/details/BusStopsAdapter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/details/LineDetailsActivity.kt
Labels: refactoring

#45 bus list에서 중복 클릭시 app이 죽는 문제 수정
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesFragment.kt
Labels: bug

#46 Refactoring - Alarm, Favorite 데이터 가져오는 로직 분리
  app/src/main/java/com/hppk/sw/hppkcommuterbus/application/CommuterBusApplication.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/local/LocalDataSource.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/model/BusLine.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/AlarmRepository.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/FavoriteRepository.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/source/local/PrefAlarmDao.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/data/repository/source/local/PrefFavoriteDao.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesAdapter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesContract.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesFragment.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesPresenter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/details/BusStopsAdapter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/details/LineDetailsActivity.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/details/LineDetailsContract.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/details/LineDetailsPresenter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/mypage/MyPageAdapter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/mypage/MyPageContract.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/mypage/MyPagePresenter.kt
Labels: refactoring

#48 App Icon 추가
  .idea/codeStyles/Project.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/strings.xml
Labels: enhancement

#47 Message가 넘어오지 않는 문제 수정 및 알람이 주기적으로 울릴 수 있도록 수정
  app/src/main/java/com/hppk/sw/hppkcommuterbus/commons/Commons.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/manager/BusAlarmManager.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/AlarmReceiver.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/GeofenceBroadcastReceiver.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/details/LineDetailsActivity.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/details/LineDetailsPresenter.kt
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug

#49 Settings에 SeekBarPreference로 변경하여 설정 값 변경하도록 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/AlarmReceiver.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/details/LineDetailsPresenter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/settings/DevelopersActivity.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/settings/SettingsActivity.kt
  app/src/main/res/layout/activity_developers.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/root_preferences.xml
Labels: main feature

#51 디자인 부분을 개선해보았습니다.
  app/src/main/java/com/hppk/sw/hppkcommuterbus/const/MapApiConst.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/manager/NotiManager.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/AlarmReceiver.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/MainActivity.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/current/CurrentFragment.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/current/CurrentPresenter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/details/LineDetailsActivity.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/mypage/MyPageAdapter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/mypage/MyPageFragment.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/splash/SplashActivity.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_alarm_normal.xml
  app/src/main/res/drawable/ic_arrow_drop_down.xml
  app/src/main/res/drawable/ic_bus.xml
  app/src/main/res/drawable/ic_dehaze.xml
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/ic_my_location.xml
  app/src/main/res/drawable/ic_person_pin.xml
  app/src/main/res/drawable/ic_point.xml
  app/src/main/res/drawable/ic_star_border.xml
  app/src/main/res/layout/activity_developers.xml
  app/src/main/res/layout/activity_line_details.xml
  app/src/main/res/layout/activity_spalsh.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_bus_list.xml
  app/src/main/res/layout/item_bus_stop.xml
  app/src/main/res/layout/item_my_page_bus_stop.xml
  app/src/main/res/layout/item_title.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: main feature

#52 Firebase Crashlytics 의존성 추가
  app/build.gradle
  build.gradle
Labels: main feature

#53 Geofence 이벤트에 대해 휴일에는 알람이 발생하지 않도록 수정
  app/src/main/java/com/hppk/sw/hppkcommuterbus/commons/Commons.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/AlarmReceiver.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/GeofenceBroadcastReceiver.kt
Labels: bug

#57 Alarm message 변경
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/AlarmReceiver.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/GeofenceBroadcastReceiver.kt
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: requirement

#60 Reboot 후 알람을 다시 등록하도록 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hppk/sw/hppkcommuterbus/manager/BusAlarmManager.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/AlarmReceiver.kt
Labels: bug

#59 출퇴근 버스 색상 다르게 표시 & Verion Up
  app/build.gradle
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/buslines/BusLinesAdapter.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/ui/mypage/MyPageAdapter.kt
Labels: enhancement

#62 FIX - Alarm 울리지 않는 문제 수정
  app/src/main/java/com/hppk/sw/hppkcommuterbus/manager/BusAlarmManager.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/AlarmReceiver.kt
  app/src/main/java/com/hppk/sw/hppkcommuterbus/receiver/GeofenceBroadcastReceiver.kt
Labels: bug
